[[ruleset]]
handled_access_fs = ["v5.all"]

# Main system directories can be read.
[[path_beneath]]
allowed_access = ["v5.read_execute"]
parent_fd = [".", "/bin", "/lib", "/usr", "/dev", "/etc", "/proc"]

# Only allow writing to /tmp.
[[path_beneath]]
allowed_access = ["v5.read_write"]
parent_fd = ["/tmp"]
